default_params: &default_params
    temperature: 0.1

models:
    agents/bom_assistant/default:
        model_type: "langchain"
        primary:
            model: "openai/gpt-4.1-mini"
            <<: *default_params

    agents/bom_generator/default:
        model_type: "langchain"
        primary:
            model: "google/gemini-2.5-flash"
            temperature: 0.0

    services/datasheet_matcher/default:
        model_type: "langchain"
        primary:
            model: "google/gemini-2.5-flash"
            temperature: 0.0
